version: '3.5'
services:

  postgres:

#    image: grufos/postgres:15.6
    build:
      context: ./docker-postgres
      dockerfile: Dockerfile
    stop_grace_period: 60s
    shm_size: '2gb'
    command: |
      -c shared_preload_libraries='plugin_debugger,plpgsql_check,pg_stat_statements,auto_explain,pg_buffercache,pg_cron,shared_ispell,pg_prewarm'
      -c shared_ispell.max_size=70MB
    volumes:
      - "/var/lib/pgsql/15_1/data:/var/lib/postgresql/data"
      - "/var/log/postgresql1:/var/log/postgresql"
      - "/mnt/pgbak2/:/mnt/pgbak/"
      - "/usr/share/postgres/15_1/tsearch_data:/usr/share/postgresql/tsearch_data"
      - "/var/lib/pgsql/15_1/app_db_init_sql:/app_db_init_sql"
    ports:
      - "5433:5432"
    environment:
      ENV_DB_VALUE: DEV
      APP_DB: "My_db"
      APP_DB_PASSWORD: qweasdzxc
#      POSTGRES_INITDB_ARGS: "--locale=ru_RU.UTF8 --data-checksums"
      POSTGRES_PASSWORD: qweasdzxc
      POSTGRES_HOST_AUTH_METHOD: trust
      DEPLOY_PASSWORD: qweasdzxc
      PGBOUNCER_PASSWORD: zxcasdqwe
#      TZ: "Etc/UTC"
      TZ: "Europe/Moscow"
      EMAILTO: "DBA-PostgreSQL@company.ru"
      EMAIL_SERVER: "mail.company.ru"
      EMAIL_HOSTNAME: "noreplay@myhost.ru"
      BACKUP_THREADS: "4"
      BACKUP_MODE: ""

  pgbouncer:
#    image: grufos/pgbouncer:1.22.0
    build:
      context: ./docker-pgbouncer
      dockerfile: Dockerfile
    volumes:
      - "/etc/pgbouncer1/:/etc/pgbouncer/"
      - "/var/log/pgbouncer1:/var/log/pgbouncer"
      - "/etc/localtime:/etc/localtime"
    ports:
      - "6433:6432"
    restart: always
    depends_on:
      - postgres
    environment:
# если в каталоге файлов есть файлы настройки то указанные ниже переменные не обрабатываются 
# если файлы настройки не указываются, то нужно передать в переменных параметры подключения.
# 1-й вариант - использование передачи через URI подключения к серверу
#      - DATABASE_URL=postgresql://postgres:qweasdzxc@127.0.0.1:5432
# 2-й вариант - отдельные переменные 
# Обязательно нужно указывать DB_PASSWORD
      - DB_USER=pgbouncer
      - DB_PASSWORD=zxcasdqwe
#      - DB_HOST=127.0.0.1
      - DB_HOST=postgres
      - DB_PORT=5432
      - AUTH_TYPE=hba

