version: '3.5'
services:

  pgprobackup_show:
    build:
      context: ./docker-pgprobackup
      dockerfile: Dockerfile

    volumes:
      - "/mnt/pgbak2/:/mnt/pgbak/"

    environment:
      TZ: "Europe/Moscow"
      EMAILTO: "DBA-PostgreSQL@interfax.ru"
      EMAIL_SERVER: "extra.devel.ifx"
      EMAIL_HOSTNAME: "noreplay@myhost.ru"
      EMAIL_SEND: "no"

    entrypoint: "/usr/local/bin/show.sh"
